/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as LabRouteImport } from './routes/lab'
import { Route as ParadeigmataRouteImport } from './routes/paradeigmata'
import { Route as PoioiEimasteRouteImport } from './routes/poioi-eimaste'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as YpiresiesRouteImport } from './routes/ypiresies'
import { Route as ElIndexRouteImport } from './routes/el/index'
import { Route as ElAboutRouteImport } from './routes/el/about'
import { Route as ElContactRouteImport } from './routes/el/contact'
import { Route as ElAuditRouteImport } from './routes/el/audit'
import { Route as ElServicesRouteImport } from './routes/el/services'
import { Route as ElSolutionsRouteImport } from './routes/el/solutions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ParadeigmataRoute = ParadeigmataRouteImport.update({
  id: '/paradeigmata',
  path: '/paradeigmata',
  getParentRoute: () => rootRouteImport,
} as any)
const PoioiEimasteRoute = PoioiEimasteRouteImport.update({
  id: '/poioi-eimaste',
  path: '/poioi-eimaste',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const YpiresiesRoute = YpiresiesRouteImport.update({
  id: '/ypiresies',
  path: '/ypiresies',
  getParentRoute: () => rootRouteImport,
} as any)

const ElIndexRoute = ElIndexRouteImport.update({
  id: '/el/',
  path: '/el/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElAboutRoute = ElAboutRouteImport.update({
  id: '/el/about',
  path: '/el/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ElContactRoute = ElContactRouteImport.update({
  id: '/el/contact',
  path: '/el/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ElAuditRoute = ElAuditRouteImport.update({
  id: '/el/audit',
  path: '/el/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ElServicesRoute = ElServicesRouteImport.update({
  id: '/el/services',
  path: '/el/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ElSolutionsRoute = ElSolutionsRouteImport.update({
  id: '/el/solutions',
  path: '/el/solutions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/audit': typeof AuditRoute
  '/lab': typeof LabRoute
  '/paradeigmata': typeof ParadeigmataRoute
  '/poioi-eimaste': typeof PoioiEimasteRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ypiresies': typeof YpiresiesRoute
  '/el/': typeof ElIndexRoute
  '/el/about': typeof ElAboutRoute
  '/el/contact': typeof ElContactRoute
  '/el/audit': typeof ElAuditRoute
  '/el/services': typeof ElServicesRoute
  '/el/solutions': typeof ElSolutionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/audit': typeof AuditRoute
  '/lab': typeof LabRoute
  '/paradeigmata': typeof ParadeigmataRoute
  '/poioi-eimaste': typeof PoioiEimasteRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ypiresies': typeof YpiresiesRoute
  '/el': typeof ElIndexRoute
  '/el/about': typeof ElAboutRoute
  '/el/contact': typeof ElContactRoute
  '/el/audit': typeof ElAuditRoute
  '/el/services': typeof ElServicesRoute
  '/el/solutions': typeof ElSolutionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/audit': typeof AuditRoute
  '/lab': typeof LabRoute
  '/paradeigmata': typeof ParadeigmataRoute
  '/poioi-eimaste': typeof PoioiEimasteRoute
  '/services': typeof ServicesRoute
  '/solutions': typeof SolutionsRoute
  '/ypiresies': typeof YpiresiesRoute
  '/el/': typeof ElIndexRoute
  '/el/about': typeof ElAboutRoute
  '/el/contact': typeof ElContactRoute
  '/el/audit': typeof ElAuditRoute
  '/el/services': typeof ElServicesRoute
  '/el/solutions': typeof ElSolutionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/contact' | '/audit' | '/lab' | '/paradeigmata' | '/poioi-eimaste' | '/services' | '/solutions' | '/ypiresies' | '/el/' | '/el/about' | '/el/contact' | '/el/audit' | '/el/services' | '/el/solutions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/audit' | '/lab' | '/paradeigmata' | '/poioi-eimaste' | '/services' | '/solutions' | '/ypiresies' | '/el' | '/el/about' | '/el/contact' | '/el/audit' | '/el/services' | '/el/solutions'
  id: '__root__' | '/' | '/about' | '/contact' | '/audit' | '/lab' | '/paradeigmata' | '/poioi-eimaste' | '/services' | '/solutions' | '/ypiresies' | '/el/' | '/el/about' | '/el/contact' | '/el/audit' | '/el/services' | '/el/solutions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AuditRoute: typeof AuditRoute
  LabRoute: typeof LabRoute
  ParadeigmataRoute: typeof ParadeigmataRoute
  PoioiEimasteRoute: typeof PoioiEimasteRoute
  ServicesRoute: typeof ServicesRoute
  SolutionsRoute: typeof SolutionsRoute
  YpiresiesRoute: typeof YpiresiesRoute
  ElIndexRoute: typeof ElIndexRoute
  ElAboutRoute: typeof ElAboutRoute
  ElContactRoute: typeof ElContactRoute
  ElAuditRoute: typeof ElAuditRoute
  ElServicesRoute: typeof ElServicesRoute
  ElSolutionsRoute: typeof ElSolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paradeigmata': {
      id: '/paradeigmata'
      path: '/paradeigmata'
      fullPath: '/paradeigmata'
      preLoaderRoute: typeof ParadeigmataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poioi-eimaste': {
      id: '/poioi-eimaste'
      path: '/poioi-eimaste'
      fullPath: '/poioi-eimaste'
      preLoaderRoute: typeof PoioiEimasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ypiresies': {
      id: '/ypiresies'
      path: '/ypiresies'
      fullPath: '/ypiresies'
      preLoaderRoute: typeof YpiresiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/': {
      id: '/el/'
      path: '/el/'
      fullPath: '/el/'
      preLoaderRoute: typeof ElIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/about': {
      id: '/el/about'
      path: '/el/about'
      fullPath: '/el/about'
      preLoaderRoute: typeof ElAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/contact': {
      id: '/el/contact'
      path: '/el/contact'
      fullPath: '/el/contact'
      preLoaderRoute: typeof ElContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/audit': {
      id: '/el/audit'
      path: '/el/audit'
      fullPath: '/el/audit'
      preLoaderRoute: typeof ElAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/services': {
      id: '/el/services'
      path: '/el/services'
      fullPath: '/el/services'
      preLoaderRoute: typeof ElServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/el/solutions': {
      id: '/el/solutions'
      path: '/el/solutions'
      fullPath: '/el/solutions'
      preLoaderRoute: typeof ElSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AuditRoute: AuditRoute,
  LabRoute: LabRoute,
  ParadeigmataRoute: ParadeigmataRoute,
  PoioiEimasteRoute: PoioiEimasteRoute,
  ServicesRoute: ServicesRoute,
  SolutionsRoute: SolutionsRoute,
  YpiresiesRoute: YpiresiesRoute,
  ElIndexRoute: ElIndexRoute,
  ElAboutRoute: ElAboutRoute,
  ElContactRoute: ElContactRoute,
  ElAuditRoute: ElAuditRoute,
  ElServicesRoute: ElServicesRoute,
  ElSolutionsRoute: ElSolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
